services:
  - type: web
    name: mysite
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn pdf_project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: PDFMANAGER
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
